workflows:
  android-debug-build:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      java: 21
      vars:
        PACKAGE_NAME: "com.aistudio.videocompressor.xptqvk"
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
